### PR TITLE
wchar_t implementation

### PR DESCRIPTION
**Pull request by 8carlosf**
it works for me.. I don't know if it is the best way, or if it can cause problems.. I'm running it on my computer just fine, just take a look (isn't that much)...
as always, feel free to change anything...
If this is to complex, my suggestion is to remove both truncate function (because they can cause trouble) and do the truncate via some linux tool (I don't know, I bet there is a easy way of doing it), and you can always recommend a solution for this in the documentation.

### CODE REVIEW

**Comment by 8carlosf** [comment]
forget it, sorry.. I'm having segfault in on of the free(), don't know why..

**Comment by sirikid** [comment]
I reproduce this segfault, its cause is either wrong arguments either bug in library.

**Comment by 8carlosf** [comment]
Do you have a deterministic way to make it happen? I can try some more debugging..
Also, I was thinking of a different approach, only convert to wchar_t before truncating the title, maybe using a statically allocated array, it will be redundant data, but may be a better solution..

**Comment by sirikid** [comment]
I comment all `free` in xtitle.c but segfault remains.

**Comment by 8carlosf** [comment]
can you debug it with valgrind? if you tell me how to segfault it every time, I could take a look at it..

**Pull request closed without merging**
