### PR TITLE
Multibyte chars support

### PR DESCRIPTION
**Pull request by sirikid**
How should I handle the encoding errors?

### CODE REVIEW

**Comment by baskerville** [comment]
Thanks. I guess we should print something appropriate on `stderr` in both cases. The encoding error for the format can be fatal but maybe not for the title, otherwise we'll break from the loop in snoop mode and have a memory leak.

**Comment by sirikid** [comment]
So fit?
```diff
diff --git a/xtitle.c b/xtitle.c
index bc2e8ea..6deb3dc 100644
--- a/xtitle.c
+++ b/xtitle.c
@@ -48,7 +48,8 @@ int main(int argc, char *argv[])
 			case 'f': {
 				size_t format_len = mbsrtowcs(NULL, (const char**)&optarg, 0, NULL);
 				if (format_len == (size_t)-1) {
-					return EXIT_FAILURE; // TODO Error handling
+					fprintf(stderr, "Error while decoding custom format string, its value doesn't changed.");
+					break;
 				}
 				wchar_t *tmp = realloc(format, sizeof(wchar_t) * format_len + 1);
 				if (format != tmp) {
@@ -232,7 +233,8 @@ void get_window_title(xcb_window_t win, wchar_t *title, size_t len) {
 		if (src != NULL) {
 			title_len = mbsrtowcs(title, (const char**)&src, title_len, NULL);
 			if (title_len == (size_t)-1) {
-				exit(EXIT_FAILURE); // TODO Error handling
+				fprintf(stderr, "Error while decoding window title (wid: 0x%lX)\n", (unsigned long)win);
+				title_len = 0;
 			}
 			title[title_len] = L'\0';
 		}
```
cc: @8carlsof

**Comment by baskerville** [comment]
I think the first error must be fatal:
```diff
-					return EXIT_FAILURE; // TODO Error handling
+					fprintf(stderr, "Can't decode the given format string: '%s'.\n", optarg);
+					return EXIT_FAILURE;
```

And the window ID should be zero-padded:
```diff
-				exit(EXIT_FAILURE); // TODO Error handling
+				fprintf(stderr, "Can't decode the title of 0x%08lX.\n", (unsigned long)win);
+				title_len = 0;
```

**Comment by sirikid** [comment]
Done

**Comment by baskerville** [comment]
Thanks. I tried the branch locally and got a segfault.

It comes from a missing ampersand in this line:
```c
mbsrtowcs(format, (const char**)optarg, format_len, NULL);
```

**Comment by sirikid** [comment]
Another confirmation of the fact that a type casts is evil.

**Comment by baskerville** [comment]
Thanks.

**Comment by sirikid** [comment]
One more thing, I forget null-terminator.
```diff
diff --git a/xtitle.c b/xtitle.c
index 533cb2b..fcc2e39 100644
--- a/xtitle.c
+++ b/xtitle.c
@@ -55,7 +55,8 @@ int main(int argc, char *argv[])
 					free(format);
 					format = tmp;
 				}
-				mbsrtowcs(format, (const char**)&optarg, format_len, NULL);
+				format_len = mbsrtowcs(format, (const char**)&optarg, format_len, NULL);
+				format[format_len] = L'\0';
 			} break;
 			case 't':
 				truncate = atoi(optarg);
```
Also, issue #5  is fixed, isn't it?

**Pull request closed without merging**
